version: '3.5'

services:
  main:
    build: .
    image: l2tasks:latest
    networks:
      - l2
    volumes:
      - ./volumes/config/:/config
    environment:
      PYTHONUNBUFFERED: 1

networks:
  l2:
    driver: bridge
    name: l2
