# This file is read by the supervisor node and represents
# possible work that can be executed.
# It loosely follows the style of docker-compose, but not
# all features are present.
#
# Example:
#
# example_sequence:
#   container1: 
#     image: l2base
#     cmd: "echo hello world"
#     volumes: 
#       - v1:v2
#     networks:
#
#   container2:
#     ...
pub:
  seqpub:
    image: "l2base"
    environment:
      topic: test_topoic
      str: hello
    network: l2
    command: "/bin/bash -c \"source /l2_msgs/install/setup.bash && ros2 topic pub --once $topic std_msgs/String \\\"data: $str\\\"\""
