version: '3.5'

services:
  main:
    build: .
    image: l2ar3sim:latest
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - .:/project
      - ./config:/root/.config/Cyberbotics/
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - l2
    command: "/bin/bash"

networks:
  l2:
    driver: bridge
    name: l2
