version: '3.5'
services:
  storage:
    build: .
    image: l2storage:latest
    environment:
      PYTHONUNBUFFERED: 1
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      #network_mode: bridge
    volumes:
      - ./volumes/files:/volume
    networks:
      - dbnet
      - l2
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      #network_mode: bridge
    # container_name: db
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      # files dir here is mounted just for debugging
      - "./volumes/files:/volume"
    networks:
      - dbnet

networks:
  l2:
    driver: bridge
    name: l2
  dbnet:
    driver: bridge
    name: dbnet
