version: '3.5'

services:
  sim:
    build: .
    image: l2sim
    ipc: host
    networks:
      - l2
    volumes:
      - "webots:/tmp"
      - "./tmp:/cfg"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "PYTHONUNBUFFERED=1"
      - "OBJCONFIG=$OBJCONFIG"
      - "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
      - "DISPLAY=$DISPLAY"
    command: /ros_entrypoint.sh ros2 run l2_sim node --ros-args -p report_path:=/test -p object_config:=$OBJCONFIG -r __ns:=/l2/$COMPOSE_PROJECT_NAME
  
  example_controller:
    build: .
    image: l2sim
    volumes:
      - "webots:/tmp"
    networks:
      - l2
    environment:
      - "WEBOTS_HOME=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/"
      - "LD_LIBRARY_PATH=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/lib/controller"
      - "WEBOTS_ROBOT_NAME=single_motor"
      - "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
    command: /ros_entrypoint.sh ros2 run l2_sim example_controller --ros-args -p synchronization:=False -r __ns:=/l2/$COMPOSE_PROJECT_NAME

  pendant_controller:
    build: .
    image: l2sim
    volumes:
      - "webots:/tmp"
    networks:
      - l2
    environment:
      - "WEBOTS_HOME=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/"
      - "LD_LIBRARY_PATH=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/lib/controller"
      - "WEBOTS_ROBOT_NAME=pendant"
      - "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
    command: /ros_entrypoint.sh ros2 run l2_sim pendant_controller --ros-args -p synchronization:=False -r __ns:=/l2/$COMPOSE_PROJECT_NAME

  range_controller:
    build: .
    image: l2sim
    ipc: container:sim
    pid: host
    volumes:
      - "webots:/tmp"
    networks:
      - l2
    environment:
      - "WEBOTS_HOME=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/"
      - "LD_LIBRARY_PATH=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/lib/controller"
      - "PYTHONFAULTHANDLER=1"
      - "PYTHONUNBUFFERED=1"
      - "WEBOTS_ROBOT_NAME=range"
      - "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
    command: /ros_entrypoint.sh ros2 run l2_sim rangefinder_controller --ros-args -p synchronization:=False -r __ns:=/l2/$COMPOSE_PROJECT_NAME

  gen_example_rvl:
    build: .
    image: l2sim
    pid: host
    networks:
      - l2
    environment:
      - "PYTHONUNBUFFERED=1"
      - "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
    command: /ros_entrypoint.sh ros2 run l2_sim gen_example_rvl --ros-args -r __ns:=/l2/$COMPOSE_PROJECT_NAME

networks:
  l2:
    driver: bridge
    name: l2

volumes:
  webots:
