version: '3.5'

services:
  supervisor:
    build: .
    image: l2supervisor:latest
    networks:
      - l2
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "./config:/config"
  testenv:
    image: l2base:latest
    pid: host
    networks:
      - l2
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - ./test:/test
    command: /bin/bash

networks:
  l2:
    driver: bridge
    name: l2
