version: "3.8"
services:
  fw_native:
    build: .
    image: l2pio
    stdin_open: true
    tty: true
    network_mode: host
    working_dir: /volume
    entrypoint: ["bash", "-c", "pio run -e native && .pio/build/native/program"]
    volumes:
      - ".:/volume"
      - "./.pio:/root/.pio"
