# Controller config for MoveIt2
# http://docs.ros.org/en/indigo/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/controller_configuration.html

controller_names:
    - arm_controller

arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

# TODO gripper controller
# https://github.com/ros-planning/moveit2/blob/eloquent/moveit_demo_nodes/run_moveit_cpp/config/controllers.yaml
