geometry_msgs/Pose pose
geometry_msgs/Vector3 scale

uint8 TYPE_UNKNOWN = 0
uint8 TYPE_CUBE = 1
uint8 type

---
bool valid # does the addition produce a valid structure?
l2_msgs/Constraint[] invalid
double score # lower score --> better 

string message # informational, e.g. for error messages
