version: "3.8"
services:
  fw_native:
    build: ./firmware/
    image: l2pio
    stdin_open: true
    tty: true
    working_dir: /volume
    entrypoint: ["bash", "-c", "pio run -e native --silent && .pio/build/native/program"]
    #ports:
    #  - "5555:5555" # Pull commands from web interface
    #  - "5556:5556" # Push state to sim (step counts)
    #networks: 
    #   - ar3
    network_mode: host
    volumes:
      - "./firmware:/volume"
      - "./firmware/.pio:/root/.pio"
      - "./firmware/.packages:/root/.platformio/packages"
  web_interface:
    build: ./control/
    image: l2ar3control:latest
    command: python3 /www/native_client.py
    working_dir: /www
    environment:
      - "PYTHONUNBUFFERED=1"
    # networks: 
    #  - ar3
    network_mode: host
    volumes:
      - "./control:/www"
    #ports:
    #  - "8000:8000" # Web server
    #  - "8001:8001" # Websocket server
  stub_robot: # Headless, basic simulation without webots
    build: ./sim/
    tty: true
    image: l2ar3sim:latest
    # networks: 
    #   - ar3
    network_mode: host  
    #ports:
    #  - "5557:5557" # Push limit values
    command: /bin/bash -i -c "ros2 run l2_ar3 node"
    stop_grace_period: 1s

networks:
  ar3:
    name: ar3
