version: '3.5'

services:
  # WARNING: local changes only possible for HTML, *not* for ROS node (which requires rebuild)
  app_local:
    image: l2app:latest
    build: .
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - l2
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes: 
      - ./src:/src
  app:
    build: .
    image: l2app:latest
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - l2
    ports:
      - "8000:8000"

networks:
  l2:
    driver: bridge
    name: l2
